const data = {
  nav: {
    title: {
      text: `Louis Iaeger V`,
      link: `#app`,
    },
    navLinks: [
      {
        name: `Home`,
        url: `#app`,
      },
      {
        name: `About`,
        url: `#about`,
      },
      {
        name: `Projects`,
        url: `#projects`,
      },
      {
        name: `Contact`,
        url: `#contact`,
      },
    ],
  },
  jumbo: {
    text: `Hi, I'm Louis. I design & build websites.`,
    buttonText: `Yes, I'm available for hire.`,
    buttonLink: `#contact`,
    scrollDownLink: '#about',
    img: `img/desk4.jpg`,
  },
  about: {
    img: `img/me.jpg`,
    aboutText: `Highly-driven Full-Stack software developer and software engineer with more than five years experience producing solutions for large corporations and local businesses. Proven skillset for designing, testing, and launching responsive software.`,
  },
  portfolio2: {
    backgroundImg: `img/zipper.png`,
    projects: [
      {
        title: `React Todos`,
        description: `Todo web app built with React. Add, edit, complete, and delete todos.`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/React-todo-image.png?raw=true`,
        link: `https://react-todo-ljfiv.netlify.app/`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `React Menu`,
        description: `A restaurant menu web app made with React`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/React-menu-image.png?raw=true`,
        link: `https://react-menu-ljfiv.netlify.app/`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `React Resume`,
        description: `A simple resume web app component made with React.`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/React-Resume-img.png?raw=true`,
        link: `https://react-resume-ljfiv.netlify.app/`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `React FAQs`,
        description: `Cryptocurrency-themed FAQ web app component made with React.`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/React-crypto-faqs.png?raw=true`,
        link: `https://react-crypto-faqs-ljfiv.netlify.app/`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `React Tours`,
        description: `World Tour Business web app made with React`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/react-tours-image.png?raw=true`,
        link: `https://react-tours-ljfiv.netlify.app/`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `Meme Maker`,
        description: `Meme creator made w/React JS and create-react-app`,
        img: `https://github.com/louisiaegerv/Project-Images/blob/master/meme-maker-cover-img-portfolio2.png?raw=true`,
        link: `https://meme-generator-13660.web.app/`,
        tags: [`JavaScript`, `React    `],
      },
      {
        title: `Breakout`,
        description: `Breakout arcade game made w/PhaserJS Framework`,
        img: `https://github.com/louisiaegerv/Project-Images/blob/master/breakout.png?raw=true`,
        link: `https://louisiaegerv.github.io/breakout/`,
        tags: [`JavaScript`, `Game Dev`],
      },
      {
        title: `LouTube`,
        description: `Simple YouTube Clone made with React`,
        img: `https://github.com/louisiaegerv/Project-Images/blob/master/loutube-wide.png?raw=true`,
        link: `https://www.youtube.com/watch?v=nr0FQeXYmws&feature=youtu.be`,
        tags: [`JavaScript`, `React`],
      },
      {
        title: `guestlist`,
        description: `Manage your party's RSVP's with this responsive web app made with JavaScript!`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/GuestListApp.jpg?raw=true`,
        link: `https://louisiaegerv.github.io/guestlist/`,
        tags: [`JavaScript`, `localstorage`],
      },
      {
        title: `stocks-nodejs`,
        description: `Get any stocks current NASDAQ price with this NodeJS app.`,
        img: `https://github.com/louisiaegerv/Project-Images/blob/master/stock2.png?raw=true`,
        link: `https://github.com/louisiaegerv/stocks-nodejs`,
        tags: [`JavaScript`, `NodeJS`, `APIs`],
      },
      {
        title: `weather-nodejs`,
        description: `Get the temp and weather for any ZIP with this NodeJS application.`,
        img: `https://raw.githubusercontent.com/louisiaegerv/Project-Images/master/weather2.png`,
        link: `https://github.com/louisiaegerv/weather-nodejs`,
        tags: [`JavaScript`, `nodeJS`, `APIs`],
      },
      {
        title: `quote`,
        description: `Random quote generator made with JavaScript & Twitter API.`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/quoteApp.jpg`,
        link: `https://louisiaegerv.github.io/quote`,
        tags: [`JavaScript`, `APIs`],
      },
      {
        title: `resume`,
        description: `My responsive online resume`,
        img: `https://github.com/louisiaegerv/resume/raw/master/assets/img/my-resume.png`,
        link: `https://louisiaegerv.github.io/resume`,
        tags: [`SASS`],
      },
      {
        title: `Zephyr Template`,
        description: `The responsive and mobile-first template site I created with ReactJS, HTML5, and CSS.`,
        img: `https://github.com/louisiaegerv/Project-Images/raw/master/ZephyrSite.jpg`,
        link: `https://louisiaegerv.github.io/zephyr/`,
        tags: [`JavaScript`, `ReactJS`],
      },
      {
        title: `Cobalt Template`,
        description: `Another responsive website theme I created using HTML and CSS`,
        img: `https://raw.githubusercontent.com/louisiaegerv/Project-Images/master/cobalt.png`,
        link: `https://louisiaegerv.github.io/cobalt`,
        tags: [`JavaScript`],
      },
      {
        title: `noteboard`,
        description: `For all those genius ideas you keep forgetting.`,
        img: `https://raw.githubusercontent.com/louisiaegerv/Project-Images/master/noteboard.png`,
        link: `https://louisiaegerv.github.io/noteboard`,
        tags: [`JavaScript`, `jQuery`],
      },
    ],
  },
  contact: {
    email: `louis.iaeger@yahoo.com`,
  },
  social: [
    {
      name: 'twitter',
      shortlink: 'twitter.com/theCodeslayer/',
      fullLink: 'https://twitter.com/theCodeslayer/',
      img: '',
      fontAwesome: true,
    },
    {
      name: 'github',
      shortlink: 'github.com/louisiaegerv/',
      fullLink: 'https://github.com/louisiaegerv/',
      img: '',
      fontAwesome: true,
    },
    {
      name: 'linkedin',
      shortlink: 'linkedin.com/in/louislinkedin',
      fullLink: 'https://www.linkedin.com/in/louislinkedin',
      img: '',
      fontAwesome: true,
    },
    {
      name: 'Codecademy',
      shortlink: 'codecademy.com/megapandalord',
      fullLink: 'https://www.codecademy.com/megapandalord',
      img: 'https://louisiaegerv.github.io/resume/assets/img/cc2w.png',
      fontAwesome: false,
    },
    {
      name: 'Team Treehouse',
      shortlink: 'teamtreehouse.com/louisiaeger',
      fullLink: 'https://teamtreehouse.com/louisiaeger',
      img:
        'https://raw.githubusercontent.com/louisiaegerv/Project-Images/master/treehouse.png',
      fontAwesome: false,
    },
  ],
}
